### ISSUE TITLE
Assign your driver id in MainFragment.java in place of "someDriverId".

### ISSUE THREAD

**Issue by maaaaagen** [zendrive/zendrive-sdk-android-sample#6]
Assign your driver id in MainFragment.java in place of "someDriverId".,How can I find the driverId,I can just find the application key.

**Comment by chandan-zendrive** [comment]
driverId needs to be set by the developer to suit your particular application. It is a unique id assigned by the app developer for every user of your app. You need to modify MainFragment.java to set this up when using this sample app.
